// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package usermanager.proxies;

public class Employee implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject employeeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UserManager.Employee";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EmployeeId("EmployeeId"),
		Title("Title"),
		Firstname("Firstname"),
		Lastname("Lastname"),
		Gender("Gender"),
		Phone("Phone"),
		Jobtitle("Jobtitle"),
		Specialty("Specialty"),
		Email("Email"),
		HasAccount("HasAccount"),
		FullName("FullName"),
		Employee_Department("UserManager.Employee_Department"),
		Employee_Department_Security("UserManager.Employee_Department_Security"),
		Employee_Account("UserManager.Employee_Account");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Employee(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Employee(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject employeeMendixObject)
	{
		if (employeeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, employeeMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.employeeMendixObject = employeeMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static usermanager.proxies.Employee initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new usermanager.proxies.Employee(context, mendixObject);
	}

	public static usermanager.proxies.Employee load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return usermanager.proxies.Employee.initialize(context, mendixObject);
	}

	public static java.util.List<usermanager.proxies.Employee> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> usermanager.proxies.Employee.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of EmployeeId
	 */
	public final java.lang.Integer getEmployeeId()
	{
		return getEmployeeId(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeId
	 */
	public final java.lang.Integer getEmployeeId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EmployeeId.toString());
	}

	/**
	 * Set value of EmployeeId
	 * @param employeeid
	 */
	public final void setEmployeeId(java.lang.Integer employeeid)
	{
		setEmployeeId(getContext(), employeeid);
	}

	/**
	 * Set value of EmployeeId
	 * @param context
	 * @param employeeid
	 */
	public final void setEmployeeId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer employeeid)
	{
		getMendixObject().setValue(context, MemberNames.EmployeeId.toString(), employeeid);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Firstname
	 */
	public final java.lang.String getFirstname()
	{
		return getFirstname(getContext());
	}

	/**
	 * @param context
	 * @return value of Firstname
	 */
	public final java.lang.String getFirstname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Firstname.toString());
	}

	/**
	 * Set value of Firstname
	 * @param firstname
	 */
	public final void setFirstname(java.lang.String firstname)
	{
		setFirstname(getContext(), firstname);
	}

	/**
	 * Set value of Firstname
	 * @param context
	 * @param firstname
	 */
	public final void setFirstname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String firstname)
	{
		getMendixObject().setValue(context, MemberNames.Firstname.toString(), firstname);
	}

	/**
	 * @return value of Lastname
	 */
	public final java.lang.String getLastname()
	{
		return getLastname(getContext());
	}

	/**
	 * @param context
	 * @return value of Lastname
	 */
	public final java.lang.String getLastname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Lastname.toString());
	}

	/**
	 * Set value of Lastname
	 * @param lastname
	 */
	public final void setLastname(java.lang.String lastname)
	{
		setLastname(getContext(), lastname);
	}

	/**
	 * Set value of Lastname
	 * @param context
	 * @param lastname
	 */
	public final void setLastname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastname)
	{
		getMendixObject().setValue(context, MemberNames.Lastname.toString(), lastname);
	}

	/**
	 * @return value of Gender
	 */
	public final java.lang.String getGender()
	{
		return getGender(getContext());
	}

	/**
	 * @param context
	 * @return value of Gender
	 */
	public final java.lang.String getGender(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Gender.toString());
	}

	/**
	 * Set value of Gender
	 * @param gender
	 */
	public final void setGender(java.lang.String gender)
	{
		setGender(getContext(), gender);
	}

	/**
	 * Set value of Gender
	 * @param context
	 * @param gender
	 */
	public final void setGender(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String gender)
	{
		getMendixObject().setValue(context, MemberNames.Gender.toString(), gender);
	}

	/**
	 * @return value of Phone
	 */
	public final java.lang.String getPhone()
	{
		return getPhone(getContext());
	}

	/**
	 * @param context
	 * @return value of Phone
	 */
	public final java.lang.String getPhone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Phone.toString());
	}

	/**
	 * Set value of Phone
	 * @param phone
	 */
	public final void setPhone(java.lang.String phone)
	{
		setPhone(getContext(), phone);
	}

	/**
	 * Set value of Phone
	 * @param context
	 * @param phone
	 */
	public final void setPhone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phone)
	{
		getMendixObject().setValue(context, MemberNames.Phone.toString(), phone);
	}

	/**
	 * Get value of Jobtitle
	 * @param jobtitle
	 */
	public final usermanager.proxies.ENUM_Jobtitle getJobtitle()
	{
		return getJobtitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Jobtitle
	 */
	public final usermanager.proxies.ENUM_Jobtitle getJobtitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Jobtitle.toString());
		if (obj == null) {
			return null;
		}
		return usermanager.proxies.ENUM_Jobtitle.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Jobtitle
	 * @param jobtitle
	 */
	public final void setJobtitle(usermanager.proxies.ENUM_Jobtitle jobtitle)
	{
		setJobtitle(getContext(), jobtitle);
	}

	/**
	 * Set value of Jobtitle
	 * @param context
	 * @param jobtitle
	 */
	public final void setJobtitle(com.mendix.systemwideinterfaces.core.IContext context, usermanager.proxies.ENUM_Jobtitle jobtitle)
	{
		if (jobtitle != null) {
			getMendixObject().setValue(context, MemberNames.Jobtitle.toString(), jobtitle.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Jobtitle.toString(), null);
		}
	}

	/**
	 * @return value of Specialty
	 */
	public final java.lang.String getSpecialty()
	{
		return getSpecialty(getContext());
	}

	/**
	 * @param context
	 * @return value of Specialty
	 */
	public final java.lang.String getSpecialty(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Specialty.toString());
	}

	/**
	 * Set value of Specialty
	 * @param specialty
	 */
	public final void setSpecialty(java.lang.String specialty)
	{
		setSpecialty(getContext(), specialty);
	}

	/**
	 * Set value of Specialty
	 * @param context
	 * @param specialty
	 */
	public final void setSpecialty(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String specialty)
	{
		getMendixObject().setValue(context, MemberNames.Specialty.toString(), specialty);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of HasAccount
	 */
	public final java.lang.Boolean getHasAccount()
	{
		return getHasAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of HasAccount
	 */
	public final java.lang.Boolean getHasAccount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasAccount.toString());
	}

	/**
	 * Set value of HasAccount
	 * @param hasaccount
	 */
	public final void setHasAccount(java.lang.Boolean hasaccount)
	{
		setHasAccount(getContext(), hasaccount);
	}

	/**
	 * Set value of HasAccount
	 * @param context
	 * @param hasaccount
	 */
	public final void setHasAccount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hasaccount)
	{
		getMendixObject().setValue(context, MemberNames.HasAccount.toString(), hasaccount);
	}

	/**
	 * @return value of FullName
	 */
	public final java.lang.String getFullName()
	{
		return getFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of FullName
	 */
	public final java.lang.String getFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FullName.toString());
	}

	/**
	 * Set value of FullName
	 * @param fullname
	 */
	public final void setFullName(java.lang.String fullname)
	{
		setFullName(getContext(), fullname);
	}

	/**
	 * Set value of FullName
	 * @param context
	 * @param fullname
	 */
	public final void setFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fullname)
	{
		getMendixObject().setValue(context, MemberNames.FullName.toString(), fullname);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Employee_Department
	 */
	public final usermanager.proxies.Department getEmployee_Department() throws com.mendix.core.CoreException
	{
		return getEmployee_Department(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee_Department
	 * @throws com.mendix.core.CoreException
	 */
	public final usermanager.proxies.Department getEmployee_Department(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usermanager.proxies.Department result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Employee_Department.toString());
		if (identifier != null) {
			result = usermanager.proxies.Department.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Employee_Department
	 * @param employee_department
	 */
	public final void setEmployee_Department(usermanager.proxies.Department employee_department)
	{
		setEmployee_Department(getContext(), employee_department);
	}

	/**
	 * Set value of Employee_Department
	 * @param context
	 * @param employee_department
	 */
	public final void setEmployee_Department(com.mendix.systemwideinterfaces.core.IContext context, usermanager.proxies.Department employee_department)
	{
		if (employee_department == null) {
			getMendixObject().setValue(context, MemberNames.Employee_Department.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Employee_Department.toString(), employee_department.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Employee_Department_Security
	 */
	public final java.util.List<usermanager.proxies.Department> getEmployee_Department_Security() throws com.mendix.core.CoreException
	{
		return getEmployee_Department_Security(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee_Department_Security
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<usermanager.proxies.Department> getEmployee_Department_Security(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<usermanager.proxies.Department> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Employee_Department_Security.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(usermanager.proxies.Department.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Employee_Department_Security
	 * @param employee_department_security
	 */
	public final void setEmployee_Department_Security(java.util.List<usermanager.proxies.Department> employee_department_security)
	{
		setEmployee_Department_Security(getContext(), employee_department_security);
	}

	/**
	 * Set value of Employee_Department_Security
	 * @param context
	 * @param employee_department_security
	 */
	public final void setEmployee_Department_Security(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<usermanager.proxies.Department> employee_department_security)
	{
		var identifiers = employee_department_security
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Employee_Department_Security.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Employee_Account
	 */
	public final administration.proxies.Account getEmployee_Account() throws com.mendix.core.CoreException
	{
		return getEmployee_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getEmployee_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Employee_Account.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Employee_Account
	 * @param employee_account
	 */
	public final void setEmployee_Account(administration.proxies.Account employee_account)
	{
		setEmployee_Account(getContext(), employee_account);
	}

	/**
	 * Set value of Employee_Account
	 * @param context
	 * @param employee_account
	 */
	public final void setEmployee_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account employee_account)
	{
		if (employee_account == null) {
			getMendixObject().setValue(context, MemberNames.Employee_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Employee_Account.toString(), employee_account.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return employeeMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final usermanager.proxies.Employee that = (usermanager.proxies.Employee) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
