// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package usermanager.proxies;

public class Shift implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject shiftMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "UserManager.Shift";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ShiftId("ShiftId"),
		StartTime("StartTime"),
		EndTime("EndTime"),
		Shift_Employee("UserManager.Shift_Employee"),
		Shift_Department("UserManager.Shift_Department");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Shift(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Shift(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject shiftMendixObject)
	{
		if (shiftMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, shiftMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.shiftMendixObject = shiftMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static usermanager.proxies.Shift initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new usermanager.proxies.Shift(context, mendixObject);
	}

	public static usermanager.proxies.Shift load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return usermanager.proxies.Shift.initialize(context, mendixObject);
	}

	public static java.util.List<usermanager.proxies.Shift> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> usermanager.proxies.Shift.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ShiftId
	 */
	public final java.lang.Long getShiftId()
	{
		return getShiftId(getContext());
	}

	/**
	 * @param context
	 * @return value of ShiftId
	 */
	public final java.lang.Long getShiftId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.ShiftId.toString());
	}

	/**
	 * Set value of ShiftId
	 * @param shiftid
	 */
	public final void setShiftId(java.lang.Long shiftid)
	{
		setShiftId(getContext(), shiftid);
	}

	/**
	 * Set value of ShiftId
	 * @param context
	 * @param shiftid
	 */
	public final void setShiftId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long shiftid)
	{
		getMendixObject().setValue(context, MemberNames.ShiftId.toString(), shiftid);
	}

	/**
	 * @return value of StartTime
	 */
	public final java.util.Date getStartTime()
	{
		return getStartTime(getContext());
	}

	/**
	 * @param context
	 * @return value of StartTime
	 */
	public final java.util.Date getStartTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartTime.toString());
	}

	/**
	 * Set value of StartTime
	 * @param starttime
	 */
	public final void setStartTime(java.util.Date starttime)
	{
		setStartTime(getContext(), starttime);
	}

	/**
	 * Set value of StartTime
	 * @param context
	 * @param starttime
	 */
	public final void setStartTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date starttime)
	{
		getMendixObject().setValue(context, MemberNames.StartTime.toString(), starttime);
	}

	/**
	 * @return value of EndTime
	 */
	public final java.util.Date getEndTime()
	{
		return getEndTime(getContext());
	}

	/**
	 * @param context
	 * @return value of EndTime
	 */
	public final java.util.Date getEndTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndTime.toString());
	}

	/**
	 * Set value of EndTime
	 * @param endtime
	 */
	public final void setEndTime(java.util.Date endtime)
	{
		setEndTime(getContext(), endtime);
	}

	/**
	 * Set value of EndTime
	 * @param context
	 * @param endtime
	 */
	public final void setEndTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date endtime)
	{
		getMendixObject().setValue(context, MemberNames.EndTime.toString(), endtime);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Shift_Employee
	 */
	public final usermanager.proxies.Employee getShift_Employee() throws com.mendix.core.CoreException
	{
		return getShift_Employee(getContext());
	}

	/**
	 * @param context
	 * @return value of Shift_Employee
	 * @throws com.mendix.core.CoreException
	 */
	public final usermanager.proxies.Employee getShift_Employee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usermanager.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Shift_Employee.toString());
		if (identifier != null) {
			result = usermanager.proxies.Employee.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Shift_Employee
	 * @param shift_employee
	 */
	public final void setShift_Employee(usermanager.proxies.Employee shift_employee)
	{
		setShift_Employee(getContext(), shift_employee);
	}

	/**
	 * Set value of Shift_Employee
	 * @param context
	 * @param shift_employee
	 */
	public final void setShift_Employee(com.mendix.systemwideinterfaces.core.IContext context, usermanager.proxies.Employee shift_employee)
	{
		if (shift_employee == null) {
			getMendixObject().setValue(context, MemberNames.Shift_Employee.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Shift_Employee.toString(), shift_employee.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Shift_Department
	 */
	public final usermanager.proxies.Department getShift_Department() throws com.mendix.core.CoreException
	{
		return getShift_Department(getContext());
	}

	/**
	 * @param context
	 * @return value of Shift_Department
	 * @throws com.mendix.core.CoreException
	 */
	public final usermanager.proxies.Department getShift_Department(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		usermanager.proxies.Department result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Shift_Department.toString());
		if (identifier != null) {
			result = usermanager.proxies.Department.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Shift_Department
	 * @param shift_department
	 */
	public final void setShift_Department(usermanager.proxies.Department shift_department)
	{
		setShift_Department(getContext(), shift_department);
	}

	/**
	 * Set value of Shift_Department
	 * @param context
	 * @param shift_department
	 */
	public final void setShift_Department(com.mendix.systemwideinterfaces.core.IContext context, usermanager.proxies.Department shift_department)
	{
		if (shift_department == null) {
			getMendixObject().setValue(context, MemberNames.Shift_Department.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Shift_Department.toString(), shift_department.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return shiftMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final usermanager.proxies.Shift that = (usermanager.proxies.Shift) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
